dist: xenial
language: python
python: 3.7

stages:
- Test-App
- Test-Docker-App


env:
  global:
  - IMAGE_NAME=christag/passwordpub
  - DOCKERHUB_USER=christag
  # DOCKERHUB_PW
  - secure: JkN81+T1GjvLvTK5gV3b+JnusQ1NTKW94eYLeqj9dQe3GrrqEdCG38WgCwv16+T1kcFlmxcfXE+7UK0iyTp5Tiw6bkMIMy3c3ezWmwcvD9HciK0RK40EC9nKYe78iiLTwNa9GOyANCavUq46rFD2Zcq3j9Ml6f6f1kXFnsOpFrGUXhgVA8FvsgwP/5tAcfEe/Db4f6hyM1DmzK+oM3Fx4o8PDVOi+ccSuXevhlTQr05qFW7XWRbiPAhZF7EAU1+e7NyRx4CrVYKAv9TzHOpJh7sNis5yogP0qq82GNtYSVvvwh9O/FIhjT15f0RvXDyk5rSl1zpEY2njWOsVeN8RBOX4gbB25nnONSUgGDMS7p3kWi2se7kfgUqNZnpp7W9INEc+Nx2aZQDZWpWzJzANW6lAu7D7TcK0voYfwAJw2vCO8cnT1pIeYv4/5sZtMpxEPNdnVy7chDqBlPGmSu5b5hXJTEiqTLhuFsxNp0YNX+hkdHIz+eRoEMogxbgUbQoFH0WML7uLa9WjuKDvFTqN7FCzvgCH4O3IKCeaNkUgLTSY4hSwzQ5rje438rNSS9s+ACQlG7aLK3XJKcIbPCU3SGb7pFJBw07QLtsJtyZcwlsWfHkYKjmA4gRV7dGlKMKDGqSpvB4AUBaoeTN64L07v8ovYATXPcNlyYuqKyPDgys=

jobs:
  include:
  - stage: Test-App
    install: pip install -r requirements
    script: pytest
  - stage: Test-Docker-App
    services: docker
    before_install:
      - docker image build -t "${IMAGE_NAME}" -f ./container/app/Dockerfile .
      - docker image ls -a
      - docker container run -d -p 5000:5000 "${IMAGE_NAME}"
    script: docker container ls | grep -q passwordpub
