# /config.yml  
password_options: # Default options for generated passwords if no parameters are supplied.
  min_char: 8 # Minimum amount of characters allowed in the password.
  max_char: 50 # Minimum amount of characters allowed in the password.
  recipe : 'WSwNWC' # The 'recipe' for the password.
  banned_ingredients : '' # Banned characters that are not allowed in a password.

generator_options:
  max_attempts: 150 # Attempts to create the password before giving up.

server_options:
  ip_address: '0.0.0.0' # Set to specific IP or set to 0.0.0.0 to listen on all IPs.
  port: '5000' # Set the port that HTTP traffic will be served.